# Generated by Django 3.2.9 on 2021-12-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=32)),
                ('make', models.CharField(max_length=32)),
                ('made_by', models.CharField(max_length=32)),
                ('hp', models.IntegerField()),
                ('history_of_productions', models.CharField(max_length=800)),
            ],
        ),
    ]
