# Generated by Django 3.2.9 on 2021-12-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0004_auto_20211206_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='top_speed',
        ),
    ]
