# Generated by Django 3.2.9 on 2021-12-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0005_auto_20211206_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price_of_the_car',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
