# Generated by Django 3.2.9 on 2021-12-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0006_auto_20211206_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_of_the_car',
        ),
    ]
