# Generated by Django 3.2.9 on 2021-12-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.CharField(default='img', max_length=700),
            preserve_default=False,
        ),
    ]
